### ISSUE TITLE
Unable to sync project , shows gradle build failed.....

### ISSUE THREAD

**Issue by ghost** [NordicSemiconductor/Android-nRF-UART#11]
![Screenshot from 2019-04-25 14-47-42](https://user-images.githubusercontent.com/49979316/56725610-d5a40000-676a-11e9-9452-263ff6f80f89.png)

**Comment by ghost** [comment]
Suggest me what can i do ????

**Comment by philips77** [comment]
Update the build tools and other dependencies to the latest ones.
