### ISSUE TITLE
Get a Secret Bluetooth Pin from My Segway Device

### ISSUE THREAD

**Issue by guyoosh1** [NordicSemiconductor/Android-nRF-UART#15]
Hello,
I'm connected via nRF UART v.2.0 to my Segway S PLUS in order to get the PIN code because there is no way of connecting to it via BL without the official app.
I just don't know what command to write in order to do get it or reset it. (screenshot attached)
any ideas? 

![PHOTO-2020-08-26-16-46-35](https://user-images.githubusercontent.com/35196237/91311861-3d81b500-e7bc-11ea-83d4-dc1ab1e41134.jpg)

**Comment by philips77** [comment]
Sorry, no idea.
