### ISSUE TITLE
Send texts longer than 20 chars

### ISSUE THREAD

**Issue by aul12** [NordicSemiconductor/Android-nRF-UART#3]
At the moment it isn't possible to send more than 20 characters at once. My application requires to send longer Strings, is there some kind of buffer size which can be configured? Do i need to split the text?

**Comment by KimSoonDong** [comment]
Yes. You need to split the text (maximum text 20 bytes).

**Comment by philips77** [comment]
You may use nRF Toolbox application if you want to send more data. When RX char is configured as Write Request the app assumes that the device supports Long Write and tries to send the whole string (max 512 bytes) as one write operation. However, if your characteristic has only the Write Command (Without Response) property it will split the text automatically into up-to-20 bytes chunks.
Also, you may there configure configurable buttons to send most common operations.

**Comment by Steven4899** [comment]
Hi, I am working on a connection to a BLE shield to send commands to a tiny TinyZero. Is there any way of sending more than 20 bytes? I also don't know how to set the RX characteristic to "Write Request". Using nRF Connect i saw that it is set to "WRITE NO RESPONSE".

**Comment by philips77** [comment]
You'd have to modify the firmware of your device and reflash it. The characteristics properties depend on the device. 
To send data longer than 20 bytes your may:
1. Request higher MTU, up to 514 bytes is supported on Android, don't know how many in your device
2. Send multiple packets using write without response and buffer then on the device side
3. Use write with response (fw modification required) and then you can write up to 512 bytes using Long Write
