### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by ghost** [NordicSemiconductor/Android-nRF-UART#9]
Please update the version of nordic UART to the latest

**Comment by philips77** [comment]
Please, use nRF Toolbox -> UART. nRF UART is in Nordic Playground and it's not fully supported.
Do you have any specific use case you need it for?

**Comment by ghost** [comment]
@philips77 Thanks for the info. I will look into it. Just trying to build the android code and learn to program BT from android end. Thanks again for pointing in the right direction. 
Best
Chandra

**Comment by philips77** [comment]
Check out this https://github.com/NordicSemiconductor/Android-BLE-Library/ library. Good luck!
Also, easy example is nRF Blinky https://github.com/NordicSemiconductor/Android-nRF-Blinky.
